### ISSUE TITLE
Unexpected arguments warning message about jax.vmap

### ISSUE THREAD

**Issue by xuliang5115** [PredictiveIntelligenceLab/Physics-informed-DeepONets#4]
Hello Sifan,
First of all, thank you for making this code public. 
I'm trying to run and understand the code of model `PI_DeepONet` for the purpose of calculating a parabolic equation problem.
I rewritte the .ipyqb file into a model package to build the project structure, and then I noticed a warning message about vmap, but I didn't have any changes to the function `operator_net`.

Being cautious about the unknown, I would like to know whether this warning happend and the how to clean this warning.
Many thanks!
[Physics-informed-DeepONets.zip](https://github.com/PredictiveIntelligenceLab/Physics-informed-DeepONets/files/7531898/Physics-informed-DeepONets.zip)

**Comment by xuliang5115** [comment]
![image](https://user-images.githubusercontent.com/49357144/141642051-56f43ad0-0cf9-4ce9-a9ab-6d65ad92f346.png)

**Comment by sifanw094** [comment]
Hi Liang,

We don't meet any warnings when running the notebook. It's better to provide more information of your warnings.

**Comment by xuliang5115** [comment]
The warning only appears in Pycharm-2021.2.3 with Physics-informed-DeepONets.py, there is no warnings when running the notebook.
