### ISSUE TITLE
Questions about Training data

### ISSUE THREAD

**Issue by Xin-yang-Liu** [PredictiveIntelligenceLab/Physics-informed-DeepONets#8]
Hi Sifan,

I am trying to reproduce the results of the Burgers' equation. I find both the ```Generate training data for boundary condition``` and ```Generate training data for PDE residual``` parts use the variable ```u0_train```, which I think should be the initial condition. Is this a typo or you intend to do this?

**Comment by WANGDI-1291** [comment]
I have the same question @Xin-yang-Liu . Have you figure it out? can you give an explaination? Thans in advance!
